# Создание нового пользователя
POST http://localhost:3000/guitar/auth-user/register HTTP/1.1
Content-Type: application/json

{
  "name": "Keks",
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Получиние информации о пользователе по ID
GET http://localhost:3000/guitar/auth-user/64274579-9211-48f4-8234-ae281e371d07 HTTP/1.1

###

# Аутентификация пользователя
POST http://localhost:3000/guitar/auth-user/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
