####################################################################################################
############################## Сервис пользователей #################################################
####################################################################################################
@userId={{login.response.body.id}}
@email={{login.response.body.email}}
@AToken={{login.response.body.accessToken}}



# Создание нового пользователя
# @name register
POST http://localhost:4000/guitar/auth-user/register HTTP/1.1
Content-Type: application/json

{
  "name": "John",
  "email": "kek01@notfound.local",
  "password": "123456"
}

###

# Получиние информации о пользователе по ID
GET http://localhost:4000/guitar/auth-user/{{userId}} HTTP/1.1
Authorization: Bearer {{AToken}}
###

# Аутентификация пользователя
# @name login
POST http://localhost:4000/guitar/auth-user/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks@gmail.com",
  "password": "123123"
}

###

# Проверка пользователя по токену
GET http://localhost:4000/guitar/auth-user/validate/{{AToken}} HTTP/1.1
Authorization: Bearer {{AToken}}

####################################################################################################
############################## Сервис публикаций ####################################################
####################################################################################################
@productId={{createProduct.response.body.id}}
###

# Создание карточки нового товара
# @name createProduct
POST http://localhost:4000/guitar/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "name": "golden guitar",
  "description": "Usque clementia talio dolorum stipes tredecim veniam. Tonsor absque volutabrum adulescens thymum demonstro degusto. Comes maiores inventore usus.\nVelit cuius ascit solium. Terminatio repellendus curatio amo. Usitas sol curto pectus absens provident ultio.\nPossimus crustulum stella delibero versus curis varietas usus. Maxime vulpes patria arcesso delicate decipio venia cupressus. Cilicium illo demum canonicus.",
  "photo": "../../../../src/assets/catalog-product-0.png",
  "type": "guitar",
  "article": "3j7xNF1eQVg11RN0000",
  "strings": 4,
  "price": 1000000
}



###

# Получить все товары

GET http://localhost:4000/guitar/products?sortDirection=desc&sortingType=price HTTP/1.1
Content-Type: application/json

###

# Получить товары с фильтром

GET http://localhost:4000/guitar/products?limit=4&sortDirection=desc&filterType=guitar,ukulele&filterStrings=12 HTTP/1.1
Content-Type: application/json

###

# Получение детальной информации по товару
GET http://localhost:4000/guitar/products/{{productId}} HTTP/1.1
Authorization: Bearer {{AToken}}
Content-Type: application/json

###

# Удаление карточки товара
DELETE http://localhost:4000/guitar/products/{{productId}} HTTP/1.1
Authorization: Bearer {{AToken}}

###

# Обновление карточки товара
PATCH http://localhost:4000/guitar/products/{{productId}} HTTP/1.1
Authorization: Bearer {{AToken}}
Content-Type: application/json

{
  "name": "golden",
  "price": 1000000
}

###
