version: '3.9'
services:
  guitar.products.postgres:
    image: postgres:14-alpine
    container_name: guitar.products.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}`
    ports:
      - 5432:5432
    volumes:
      - guitar.postgres.products:/var/lib/postgresql/data

    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d {POSTGRES_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - guitar.products

  guitar.products.pgadmin:
    image: dpage/pgadmin4
    container_name: guitar.products.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8082:80
    depends_on:
      - guitar.products.postgres
    networks:
      - guitar.products

  guitar.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: 'guitar.notify.fakesmtp'
    hostname: 'guitar.notify.fakesmtp'
    ports:
      - '8025:8025'
      - '1083:8080'

  guitar.notify.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: guitar.notify.rabbitmq

    ports:
      - '1088:15672'
      - '5672:5672'

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  guitar.postgres.products:

networks:
  guitar.products:
    driver: bridge
